config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'to_dos#index'
  resources :to_dos
  get "/toggle_checkbox/:to_do_id" => "to_dos#toggle_checkbox", as: 'toggle_checkbox'
  patch "/re_sort" => 'to_dos#re_sort', as: 're_sort'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  validates :desc, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      user.image_url = auth.info.image + "type=large" # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  def index
    @to_dos = ToDo.order(:position  )
  end

  def create
    @to_do = ToDo.new(to_do_params)
    respond_to do |format|
      if @to_do.save
        # client = Twilio::REST::Client.new(Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token)
        # message = client.messages.create(from: "(713) 597-6652", to: "(281) 682-4786", body: "You've added a new to-do: #{@to_do.desc}")

        format.html { redirect_to root_url }
        format.js
      else
        format.html { redirect_to root_url, notice: 'Your to-do item was invalid'}
      end
    end

  end

  def destroy
    @to_do = ToDo.find(params[:id])
    @to_do.destroy
    respond_to do |format|
      format.js
    end
  end

  def edit
    @to_do = ToDo.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @to_do = ToDo.find(params[:id])
    @to_do.update_attributes(to_do_params)

    respond_to do |format|
      format.js
    end
  end

  def toggle_checkbox
    @to_do = ToDo.find(params[:to_do_id])
    @to_do.completed == true ? @to_do.completed = false : @to_do.completed = true
    # if @to_do.completed == true
    #   @to_do.completed = false
    # else
    #   @to_do.completed = true
    # end

    puts @to_do.inspect
    @to_do.save

    respond_to do |format|
      format.js
    end
  end

  def re_sort
    params[:to_do].each_with_index do |id, index|
      to_do = ToDo.find(id)
      to_do.position = index + 1
      to_do.save
    end


    render :nothing => true, :status => 200, :content_type => 'text/html'

  end

  private

    def to_do_params
      params.require(:to_do).permit(:desc)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, "users/edit" %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



  <% if notice %>
    <div class="alert alert-warning alert-dismissible" role="notice">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>



<%= yield %>

</body>
</html>

app/views/to_dos/_form.html.erb
<% if to_do.id %>
  <%= form_for(to_do, remote: true, html: { class: "inline-form edit_to_do_#{to_do.id}"}) do |f| %>
    <div class="form-group">
      <%= f.label :desc, class: 'sr-only' %>
      <%= f.text_field :desc, class: 'form-control', placeholder: 'Add your to-do item here...' %>
    </div>
  <% end %>
<% else %>
  <%= form_for(to_do, remote: true) do |f| %>
  <div class="form-group">
    <%= f.label :desc, class: 'sr-only' %>
    <%= f.text_field :desc, class: 'form-control', placeholder: 'Add your to-do item here...' %>
  </div>
  <% end %>
<% end %>

app/views/to_dos/_to_do.html.erb
<li id="to_do_<%= to_do.id %>" class="list-group-item">
  <span class="pull-left to-do-checkbox">
    <%= link_to toggle_checkbox_url(to_do.id), remote: true do  %>
      <% if to_do.completed %>
        <%= icon('check-square-o','', class: 'fa-2x') %>
      <% else %>
        <%= icon('square-o','', class: 'fa-2x') %>
      <% end %>
    <% end %>
  </span>
  <span class="desc"><%= to_do.desc %></span>
  <div class="pull-right">
    <a href="<%= edit_to_do_url(to_do) %>" class="btn btn-warning" data-remote="true"><%= icon('pencil-square-o') %></a>
    <a href="<%= to_do_url(to_do) %>" class="btn btn-danger" data-remote="true" data-method="delete"><%= icon('trash-o') %></a>
  </div>
</li>

app/views/to_dos/create.js.erb
$('ul.list-group').append('<%= j(render('to_do', to_do: @to_do)) %>');
$('#to_do_desc').val('');

$('li#to_do_<%= @to_do.id %>').hide();
$('li#to_do_<%= @to_do.id %>').fadeIn();

app/views/to_dos/destroy.js.erb
$("#to_do_<%= @to_do.id %>").fadeOut();

app/views/to_dos/edit.js.erb
$('li#to_do_<%= @to_do.id %> span.desc').remove();
$('li#to_do_<%= @to_do.id %>').prepend('<%= j(render('form', to_do: @to_do)) %>');

app/views/to_dos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>My ToDos</h1>
      <%= render 'form', to_do: ToDo.new %>
      <ul class="list-group">
        <% @to_dos.each do |to_do| %>
          <%= render 'to_do', to_do: to_do %>
        <% end %>
    </div>
  </div>
</div>



<script>
  $('ul.list-group').sortable({
    axis: "y",
    opacity: 0.7,
    update: function() {
      $.ajax({
        url: "<%= re_sort_url %>",
        type: 'PATCH',
        data: $('ul.list-group').sortable('serialize'),
      });
    }
  });
</script>

app/views/to_dos/toggle_checkbox.js.erb
$('#to_do_<%= @to_do.id %>').replaceWith("<%= j(render 'to_do', to_do: @to_do ) %>");

app/views/to_dos/update.js.erb
$('#edit_to_do_<%= @to_do.id %>').replaceWith("<span class=\"desc\"><%= @to_do.desc %></span>");